cabal-version: 3.0
name:          cardpg-api
version:       0.1.0.0
license:       BSD-3-Clause
license-file:  LICENSE
author:        Antigravity
maintainer:    antigravity@example.com
build-type:    Simple

common project-config
  default-language:   GHC2021
  default-extensions:
    DerivingStrategies
    DuplicateRecordFields
    MultiWayIf
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    QuantifiedConstraints
    RecordWildCards
    TemplateHaskell

library
  import:          project-config
  hs-source-dirs:  src

  -- cabal-fmt: expand src
  exposed-modules:
    CardPG.Api.Frontend
    CardPG.Api.Reflex
    CardPG.Api.Types

  build-depends:
    , aeson
    , aeson-typescript
    , base              >=4.7 && <5
    , cardpg-core
    , containers
    , random
    , text
    , time
    , uuid

executable codegen
  import:         project-config
  main-is:        Main.hs

  -- cabal-fmt: expand app -Main
  other-modules:
    DeriveSpecialized
    TypeScriptInstances

  hs-source-dirs: app
  build-depends:
    , aeson
    , aeson-typescript
    , base              >=4.7 && <5
    , cardpg-api
    , cardpg-core
    , containers
    , template-haskell
    , text
