cabal-version: 3.0
name: cardpg-core
version: 0.1.0.0
build-type: Simple
license: BSD-3-Clause
license-file: LICENSE

common project-config
  default-language: GHC2021
  default-extensions:
    -- Project Standard
    DerivingStrategies
    DuplicateRecordFields
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    QuantifiedConstraints
    RecordWildCards
    TemplateHaskell

    -- Control Flow
    MultiWayIf

library
  import: project-config
  hs-source-dirs: src
  ghc-options:
    -Wall -Wredundant-constraints -Wincomplete-uni-patterns
    -Wincomplete-record-updates -O -threaded -fno-show-valid-hole-fits
  build-depends: base >= 4.16 && < 5
               , aeson
               , text
               , vector
               , containers
               , generic-lens
               , megaparsec
               , uuid
               , random
               , optics
               , optics-th
               , mtl
               , transformers
  exposed-modules:
    CardPG.Core.State
    CardPG.Core.Logic.Monad
    
    CardPG.Core.Logic.Deck
    CardPG.Core.Logic.Planning
    CardPG.Core.Logic.Combat
    CardPG.Core.Logic.Status
    CardPG.Core.Logic.Bot
    CardPG.Core.Hardcoded
    CardPG.Core.Card
    CardPG.Core.Primitives
    CardPG.Core.Util
    CardPG.Core.Json
    CardPG.Core.RichText
    CardPG.Core.DSL.Parser
    CardPG.Core.DSL.Printer
    CardPG.Core.RuleDefs
    CardPG.Core.RuleInstances
    CardPG.Core.TextFmt
    CardPG.Core.NonEmptyText

test-suite cardpg-core-test
  import: project-config
  type: exitcode-stdio-1.0
  main-is: Main.hs
  other-modules: 
    ArbitraryInstances
    StateTests
    RuleJsonTest
    StatusParsingTest
    ConsequenceParsingTest
    ReadmeExamplesTest
    ResolutionTests
    CardPG.Core.LogicTest
  hs-source-dirs: tests
  ghc-options:
    -Wall -Wredundant-constraints -Wincomplete-uni-patterns
    -Wincomplete-record-updates -O -fno-show-valid-hole-fits
  build-depends: base
               , cardpg-core
               , aeson
               , text
               , vector
               , containers
               , QuickCheck
               , tasty
               , tasty-quickcheck
               , tasty-hunit
               , generic-random
               , bytestring
               , yaml
               , uuid
               , random
               , random
               , mtl
               , optics
