name: cardpg-core
version: 0.1.0.0
cabal-version: >= 1.10
build-type: Simple
license: BSD3
license-file: LICENSE

library
  hs-source-dirs: src
  ghc-options:
    -Wall -Wredundant-constraints -Wincomplete-uni-patterns
    -Wincomplete-record-updates -O -threaded -fno-show-valid-hole-fits
  build-depends: base >= 4.16 && < 5
               , aeson
               , text
               , vector
               , containers
               , generic-lens
               , megaparsec
               , uuid
               , random
               , optics
               , optics-th
  default-extensions:
    ConstraintKinds
    DataKinds
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    DuplicateRecordFields
    FlexibleContexts
    FlexibleInstances
    GADTs
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    MultiWayIf
    OverloadedLabels
    OverloadedStrings
    QuantifiedConstraints
    RankNTypes
    RecursiveDo
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    UndecidableInstances
  exposed-modules:
    CardPG.Core.State
    CardPG.Core.Logic
    CardPG.Core.Hardcoded
    CardPG.Core.Card
    CardPG.Core.Primitives
    CardPG.Core.Util
    CardPG.Core.Json
    CardPG.Core.RichText
    CardPG.Core.DSL.Parser
    CardPG.Core.DSL.Printer
    CardPG.Core.RuleDefs
    CardPG.Core.RuleInstances
    CardPG.Core.TextFmt
    CardPG.Core.NonEmptyText
  default-language: Haskell2010

test-suite cardpg-core-test
  type: exitcode-stdio-1.0
  main-is: Main.hs
  other-modules: 
    ArbitraryInstances
    StateTests
    RuleJsonTest
    StatusParsingTest
    ConsequenceParsingTest
    ReadmeExamplesTest
  hs-source-dirs: tests
  ghc-options:
    -Wall -Wredundant-constraints -Wincomplete-uni-patterns
    -Wincomplete-record-updates -O -fno-show-valid-hole-fits
  build-depends: base
               , cardpg-core
               , aeson
               , text
               , vector
               , containers
               , QuickCheck
               , tasty
               , tasty-quickcheck
               , tasty-hunit
               , generic-random
               , bytestring
               , yaml
               , uuid
               , random
  default-language: Haskell2010
