cabal-version:      3.0
name:               shake-build
version:            0.1.0.0
synopsis:           Shake build system for CardPG
license:            BSD-3-Clause
author:             Antigravity
maintainer:         antigravity@google.com
build-type:         Simple

common warnings
    ghc-options: -Wall

executable shake-build
    import:           warnings
    main-is:          Main.hs
    build-depends:    base >= 4.16 && < 5
                    , shake
                    , yaml
                    , aeson
                    , text
                    , directory
                    , filepath
                    , containers
                    , vector
                    , bytestring
                    , unordered-containers
                    , extra
    other-modules:    Common
                    , Rules.Cards
                    , Rules.Codegen
                    , Rules.Deploy
                    , Rules.Frontend
                    , Rules.Haskell
                    , Rules.Justfile
                    , Rules.Orchestration
    hs-source-dirs:   src
    default-language: Haskell2010
