{-# LANGUAGE GADTs #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RankNTypes #-}

module Main where

import Control.Monad (forM, join)
import Data.Function (on)
import Data.List qualified as List
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.IO qualified as T
import Data.Void (Void)
import System.Directory (doesDirectoryExist, listDirectory)
import System.FilePath (takeExtension, (</>))
import Text.Megaparsec
import Text.Megaparsec.Char
import Text.Megaparsec.Char.Lexer qualified as L

import Frontend.Style.Core (Prop (..), renderAll)
import Frontend.Style.DSL qualified as S

type Parser = Parsec Void Text

main :: IO ()
main = do
  putStrLn "Generating CSS..."
  files <- findHaskellFiles "client-reflex/src"
  putStrLn $ "Scanning " <> show (length files) <> " files..."

  scanned <- fmap concat $ forM files $ \file -> do
    content <- T.readFile file
    return $ scanContent content

  let allProps = concat staticStyles ++ scanned
      uniqueBase = List.nubBy ((==) `on` (.propClassName)) allProps
      withVariants = concatMap (\p -> [p, S.hoverProp p, S.activeProp p]) uniqueBase
      unique = List.nubBy ((==) `on` (.propClassName)) withVariants

  let header =
        "/* This file is auto-generated by client-reflex/app/GenCss.hs */\n/* Run 'cabal run gen-css' to update */\n"
  T.writeFile "client-reflex/static/atomic.css" (header <> renderAll unique)
  putStrLn $ "Done. Wrote client-reflex/static/atomic.css with " <> show (length unique) <> " rules."

-- | Recursive file finder
findHaskellFiles :: FilePath -> IO [FilePath]
findHaskellFiles top = do
  isDir <- doesDirectoryExist top
  if isDir
    then do
      entries <- listDirectory top
      paths <- forM entries $ \e -> findHaskellFiles (top </> e)
      return $ concat paths
    else
      return [top | takeExtension top == ".hs"]

-- | Static styles that don't take parameters
staticStyles :: [[Prop]]
staticStyles =
  map
    ($ [])
    [ S.flex
    , S.flexRow
    , S.flexCol
    , S.itemsCenter
    , S.itemsEnd
    , S.itemsStretch
    , S.justifyStart
    , S.justifyCenter
    , S.justifyBetween
    , S.justifyAround
    , S.grow
    , S.grow0
    , S.shrink0
    , S.absolute
    , S.relative
    , S.fixed
    , S.hidden
    , S.overflowHidden
    , S.overflowYAuto
    , S.z10
    , S.z20
    , S.z30
    , S.z40
    , S.cursorPointer
    , S.cursorNotAllowed
    , S.pointerEventsNone
    , S.pointerEventsAuto
    , S.group
    , S.inlineBlock
    , S.alignTextBottom
    , S.flexWrap
    , S.contentStart
    , S.wFull
    , S.hFull
    , S.wFit
    , S.w4
    , S.h4
    , S.w6
    , S.h6
    , S.w8
    , S.h8
    , S.w10
    , S.h10
    , S.w40
    , S.w72
    , S.w80
    , S.wCard
    , S.hCard
    , S.w8mm
    , S.h8mm
    , S.hScreen
    , S.h2_5
    , S.p1
    , S.p2mm
    , S.p2_5mm
    , S.p4
    , S.p1_5
    , S.pb1
    , S.pr1
    , S.px1
    , S.px2
    , S.py1
    , S.px4
    , S.py2
    , S.p2
    , S.px6
    , S.px8
    , S.top1
    , S.right1
    , S.py3
    , S.p3
    , S.mb2mm
    , S.mt2
    , S.mt1
    , S.mb1
    , S.mb2
    , S.top2mm
    , S.right2mm
    , S.gap0
    , S.gap1
    , S.gap2
    , S.gap4
    , S.gap4mm
    , S.bottom0
    , S.left0
    , S.right0
    , S.inset0
    , S.bgSlate900
    , S.bgSlate800
    , S.bgSlate700
    , S.bgSlate600
    , S.bgSlate950
    , S.bgSlate800_50
    , S.bgGray300
    , S.bgWhite
    , S.bgTransparent
    , S.bgIndigo600
    , S.bgIndigo500
    , S.bgIndigo700
    , S.textIndigo400
    , S.bgRed900_50
    , S.bgRed800_50
    , S.textSlate100
    , S.textSlate200
    , S.textSlate300
    , S.textBlue300
    , S.textBlue400
    , S.textSlate400
    , S.textSlate500
    , S.textSlate600
    , S.textSlate700
    , S.textBlack
    , S.textWhite
    , S.textRed500
    , S.textRed200
    , S.textRed100
    , S.textRed300
    , S.textRed400
    , S.textYellow400
    , S.textBlue500
    , S.textBlue5
    , S.borderSlate500
    , S.borderSlate600
    , S.borderSlate700
    , S.borderSlate800
    , S.borderBlack
    , S.borderTransparent
    , S.borderRed800
    , S.border
    , S.border0
    , S.border2
    , S.borderB
    , S.borderT
    , S.borderL
    , S.borderR
    , S.border02mm
    , S.rounded
    , S.roundedNone
    , S.roundedXl
    , S.rounded3Xl
    , S.roundedFull
    , S.rounded3mm
    , S.rounded2mm
    , S.rounded1mm
    , S.fontBold
    , S.textSm
    , S.textXs
    , S.textXl
    , S.text2Xl
    , S.textLg
    , S.textBase
    , S.textCenter
    , S.leadingTight
    , S.uppercase
    , S.trackingWider
    , S.whitespaceNowrap
    , S.textTruncate
    , S.textLeft
    , S.shadow2Xl
    , S.shadowXl
    , S.shadowLg
    , S.shadowSm
    , S.grayscale
    , S.grayscale50
    , S.opacity75
    , S.opacity50
    , S.backdropBlurMd
    , S.aspect43
    , S.aspectCard
    , S.aspectSquare
    , S.wCardHand
    , S.mlCardOverlap
    , S.originBottom
    , S.translateYNeg4
    , S.translateYNeg8
    , S.scale105
    , S.transitionAll
    , S.transitionTransform
    , S.transitionColors
    , S.duration200
    , S.easeOut
    , S.selectNone
    , S.ring2
    , S.ringBlue400
    , S.ringAmber400
    , S.ringIndigo400
    , S.ringOffset2
    , S.flex1
    , S.full
    ]

-- | Parameterized functions
data ParamFn = forall a. ParamFn
  { fnName :: Text
  , fnParse :: Parser a
  , fnApply :: a -> [Prop]
  }

knownParams :: [ParamFn]
knownParams =
  [ ParamFn "gap" parseInt (\n -> S.gap n [])
  , ParamFn "pad" parseInt (\n -> S.pad n [])
  , ParamFn "fontSize" parseInt (\n -> S.fontSize n [])
  , ParamFn "zIndex" parseInt (\n -> S.zIndex n [])
  , ParamFn "opacity" parseFloat (\d -> S.opacity d [])
  , ParamFn "borderRadius" parseInt (\n -> S.borderRadius n [])
  , ParamFn "css" parseThreeStrings (\(n, p, v) -> S.css n p v [])
  , ParamFn "css'" parseNameAndDecls (\(n, ds) -> S.css' n ds [])
  ]

scanContent :: Text -> [Prop]
scanContent content = case parse (many parseAny) "" content of
  Left _ -> []
  Right parsedChunks -> concat parsedChunks
  where
    parseAny :: Parser [Prop]
    parseAny = try parseParam <|> (anySingle >> return [])

    parseParam :: Parser [Prop]
    parseParam = do
      _ <- optional (string "S.")
      choice $ map tryParam knownParams

    tryParam :: ParamFn -> Parser [Prop]
    tryParam (ParamFn name p applyFn) = do
      _ <- string name
      space1
      arg <- p
      return $ applyFn arg

-- | Parsers
parseInt :: Parser Int
parseInt = L.signed space L.decimal

parseFloat :: Parser Double
parseFloat = L.signed space L.float <|> (fromIntegral <$> parseInt)

parseStringLiteral :: Parser Text
parseStringLiteral = do
  _ <- char '"'
  content <- many (try escapedChar <|> noneOf ("\"\\" :: String))
  _ <- char '"'
  return $ T.pack content

escapedChar :: Parser Char
escapedChar = do
  _ <- char '\\'
  c <- anySingle
  return $ case c of
    'n' -> '\n'
    'r' -> '\r'
    't' -> '\t'
    '\\' -> '\\'
    '"' -> '"'
    _ -> c

parseThreeStrings :: Parser (Text, Text, Text)
parseThreeStrings = do
  n <- parseStringLiteral
  space1
  p <- parseStringLiteral
  space1
  v <- parseStringLiteral
  return (n, p, v)

parseNameAndDecls :: Parser (Text, [(Text, Text)])
parseNameAndDecls = do
  n <- parseStringLiteral
  space1
  _ <- char '['
  space
  ds <- sepBy parseDecl (space >> char ',' >> space)
  space
  _ <- char ']'
  return (n, ds)

parseDecl :: Parser (Text, Text)
parseDecl = do
  _ <- char '('
  space
  p <- parseStringLiteral
  space
  _ <- char ','
  space
  v <- parseStringLiteral
  space
  _ <- char ')'
  return (p, v)
