{-# LANGUAGE FieldSelectors #-}
{-# LANGUAGE OverloadedStrings #-}

-- | CSS Generator
-- This executable generates the static CSS file from the atomic classes
-- defined in the Frontend.Style modules.
--
-- The approach: We combine runtime collection from the Catalog (to catch
-- dynamic/combinator classes like `flexCol`) with static source scanning
-- (to catch `atom` definitions not present in the catalog).
module Main where

import Control.Monad (forM)
import Data.Either (rights)
import Data.IORef (newIORef)
import Data.List qualified as List
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.IO qualified as T
import Data.Void (Void)
import System.Directory (doesDirectoryExist, listDirectory)
import System.FilePath (takeExtension, (</>))
import Text.Megaparsec
import Text.Megaparsec.Char
import Text.Megaparsec.Char.Lexer qualified as L
import Web.Atomic (utility)
import Web.Atomic.Types (ClassName (..), Rule (..))
import Web.Atomic.Types.Selector (Media (..))
import Web.Atomic.Types.Style (Declaration (..), Property (..), Style (..))
import Web.Atomic.Types.Styleable (CSS (..))

import Reflex.Dom.Builder.Static (StaticDomBuilderEnv (..))
import Reflex.Dom.Core (StaticDomBuilderT, runStaticDomBuilderT)
import Reflex.PerformEvent.Base (PerformEventT, hostPerformEventT)
import Reflex.Spider (Spider)
import Reflex.Spider.Internal (Global, SpiderHost, runSpiderHost)

import Frontend.Catalog (catalogWidget)
import Frontend.Style.T (StyleWriterT, runStyleWriterT)

type Parser = Parsec Void Text

main :: IO ()
main = do
  putStrLn "Generating CSS..."

  -- 1. Scan source files
  files <- findHaskellFiles "client-reflex/src"
  putStrLn $ "Scanning " <> show (length files) <> " files..."

  foundRules <- fmap concat $ forM files $ \file -> do
    content <- T.readFile file
    case parse (many (try parseAtom <|> (anySingle >> return []))) "" content of
      Left _ -> return []
      Right ruleLists -> return (concat ruleLists)

  putStrLn $ "Found " <> show (length foundRules) <> " atomic rules from source."

  -- 2. Run the catalog widget to collect styles
  replaceKeyRef <- newIORef 0
  let env = StaticDomBuilderEnv True Nothing replaceKeyRef

  let widget =
        catalogWidget
          :: StaticDomBuilderT Spider (StyleWriterT (PerformEventT Spider (SpiderHost Global))) ()
  let runner = runStaticDomBuilderT widget env
  let pRunner = runStyleWriterT runner

  ((_, _), collectedRules) <- runSpiderHost $ do
    (res, _events) <- hostPerformEventT pRunner
    return res

  putStrLn $ "Collected " <> show (length collectedRules) <> " rules from Catalog."

  -- 3. Combine
  let allRules = foundRules ++ collectedRules
      uniqueRules = List.nub allRules
      cssOutput = renderCssList uniqueRules

  let header =
        "/* This file is auto-generated by client-reflex/app/GenCss.hs */\n/* Run 'cabal run gen-css' to update */\n"
  T.writeFile "client-reflex/static/atomic.css" (header <> cssOutput)
  putStrLn $
    "Done. Wrote client-reflex/static/atomic.css with " <> show (length uniqueRules) <> " rules."

-- | Recursive file finder
findHaskellFiles :: FilePath -> IO [FilePath]
findHaskellFiles top = do
  isDir <- doesDirectoryExist top
  if isDir
    then do
      entries <- listDirectory top
      paths <- forM entries $ \e -> findHaskellFiles (top </> e)
      return $ concat paths
    else
      return [top | takeExtension top == ".hs"]

-- | Parser for `atom "name" "prop" "val"`
-- Returns a list of Rules
parseAtom :: Parser [Rule]
parseAtom = do
  _ <- string "atom"
  space
  name <- stringLiteral
  space
  prop <- stringLiteral
  space
  val <- stringLiteral

  -- Create the rule
  let (CSS rs) = utility (ClassName name) [Property prop :. Style (T.unpack val)] mempty :: CSS [Rule]
  return rs

-- | Parse a string literal (quoted)
stringLiteral :: Parser Text
stringLiteral = do
  _ <- char '"'
  content <- many (try escapedChar <|> noneOf ("\"\\" :: String))
  _ <- char '"'
  return $ T.pack content

escapedChar :: Parser Char
escapedChar = do
  _ <- char '\\'
  c <- anySingle
  return $ case c of
    'n' -> '\n'
    'r' -> '\r'
    't' -> '\t'
    '\\' -> '\\'
    '"' -> '"'
    _ -> c

-- | Render list of rules to CSS text
renderCssList :: [Rule] -> T.Text
renderCssList rs = T.unlines $ map renderRule rs

-- | Render a single rule
renderRule :: Rule -> T.Text
renderRule (Rule c _ med props) =
  let sel = case c of ClassName t -> escapeCssClass t
      block = "." <> sel <> " { " <> renderProps props <> " }"
   in case med of
        [] -> block
        ms -> "@media " <> renderMedia ms <> " { " <> block <> " }"

-- | Render properties
renderProps :: [Declaration] -> T.Text
renderProps ds = T.intercalate " " $ map renderDecl ds

renderDecl :: Declaration -> T.Text
renderDecl (Property p :. Style s) = p <> ": " <> T.pack s <> ";"

-- | Render media queries
renderMedia :: [Media] -> T.Text
renderMedia ms = T.intercalate " and " $ map renderOneMedia ms

renderOneMedia :: Media -> T.Text
renderOneMedia (MinWidth i) = "(min-width: " <> T.pack (show i) <> "px)"
renderOneMedia (MaxWidth i) = "(max-width: " <> T.pack (show i) <> "px)"

-- | Escape CSS class name (simple version)
escapeCssClass :: T.Text -> T.Text
escapeCssClass = T.concatMap escapeChar
  where
    escapeChar c
      | c `elem` ("!\"#$%&'()*+,./:;<=>?@[\\]^`{|}~" :: String) = "\\" <> T.singleton c
      | otherwise = T.singleton c
