# Justfile generated by shake-build
# DO NOT EDIT MANUALLY: Run 'just gen-just' to update

default: build

# Define output binary path
shake := '_build/shake-build'

# Helper to ensure shake binary exists
bootstrap:
    cabal install shake-build --installdir=_build --install-method=copy --overwrite-policy=always

# Clean build artifacts
clean:
    @test -f {{shake}} || just bootstrap
    @{{shake}} clean

# Regenerate the Justfile
gen-just:
    cabal run shake-build -- gen-just

# Generate TypeScript types
gen-types:
    @test -f {{shake}} || just bootstrap
    @{{shake}} gen-types

# Alias for gen-types
codegen:
    @test -f {{shake}} || just bootstrap
    @{{shake}} codegen

# Build cardpg-api
build-api:
    @test -f {{shake}} || just bootstrap
    @{{shake}} build-api

# Build cardpg-core
build-core:
    @test -f {{shake}} || just bootstrap
    @{{shake}} build-core

# Build cardpg-server
build-server:
    @test -f {{shake}} || just bootstrap
    @{{shake}} build-server

# Build all targets
build:
    @test -f {{shake}} || just bootstrap
    @{{shake}} build

# Run dev servers
dev:
    @test -f {{shake}} || just bootstrap
    @{{shake}} dev

# Run all tests
test:
    @test -f {{shake}} || just bootstrap
    @{{shake}} test

# Lint backend code
lint-backend:
    @test -f {{shake}} || just bootstrap
    @{{shake}} lint-backend

# Lint all code
lint:
    @test -f {{shake}} || just bootstrap
    @{{shake}} lint

# Lint frontend code
lint-frontend:
    @test -f {{shake}} || just bootstrap
    @{{shake}} lint-frontend

# Typecheck frontend code
check-types:
    @test -f {{shake}} || just bootstrap
    @{{shake}} check-types

# Test cardpg-core
test-core:
    @test -f {{shake}} || just bootstrap
    @{{shake}} test-core

# Test cardpg-server
test-server:
    @test -f {{shake}} || just bootstrap
    @{{shake}} test-server

# REPL for cardpg-api
repl-api:
    @test -f {{shake}} || just bootstrap
    @{{shake}} repl-api

# REPL for cardpg-core
repl-core:
    @test -f {{shake}} || just bootstrap
    @{{shake}} repl-core

# REPL for cardpg-server
repl-server:
    @test -f {{shake}} || just bootstrap
    @{{shake}} repl-server

# Deploy to prod (smart rebuild)
deploy-prod:
    @test -f {{shake}} || just bootstrap
    @{{shake}} deploy-prod

# Deploy to prod (force rebuild)
deploy-rebuild:
    @test -f {{shake}} || just bootstrap
    @{{shake}} deploy-rebuild

# Format code
format:
    @test -f {{shake}} || just bootstrap
    @{{shake}} format

# Check code formatting
format-check:
    @test -f {{shake}} || just bootstrap
    @{{shake}} format-check

# Run integration tests
test-integration:
    @test -f {{shake}} || just bootstrap
    @{{shake}} test-integration

