# Justfile generated by shake-build
# DO NOT EDIT MANUALLY: Run 'just gen-just' to update

default: card-data

# Define output binary path
shake := '_build/shake-build'

# Helper to ensure shake binary exists
bootstrap:
    cabal install shake-build --installdir=_build --install-method=copy --overwrite-policy=always

# Compiles all card data to VTT JSON
card-data:
    @test -f {{shake}} || just bootstrap
    @{{shake}} card-data

# Syncs card data from Google Sheets
sync:
    @test -f {{shake}} || just bootstrap
    @{{shake}} sync

# Clean build artifacts
clean:
    @test -f {{shake}} || just bootstrap
    @{{shake}} clean

# Regenerate the Justfile
gen-just:
    cabal run shake-build -- gen-just

# Generate TypeScript types
gen-types:
    @test -f {{shake}} || just bootstrap
    @{{shake}} gen-types

# Build cardpg-core
build-core:
    @test -f {{shake}} || just bootstrap
    @{{shake}} build-core

# Build cardpg-server
build-server:
    @test -f {{shake}} || just bootstrap
    @{{shake}} build-server

# Build all targets
build:
    @test -f {{shake}} || just bootstrap
    @{{shake}} build

# Run dev servers
dev:
    @test -f {{shake}} || just bootstrap
    @{{shake}} dev

# Run all tests
test:
    @test -f {{shake}} || just bootstrap
    @{{shake}} test

# Lint frontend code
lint-frontend:
    @test -f {{shake}} || just bootstrap
    @{{shake}} lint-frontend

# Typecheck frontend code
check-types:
    @test -f {{shake}} || just bootstrap
    @{{shake}} check-types

# Test cardpg-core
test-core:
    @test -f {{shake}} || just bootstrap
    @{{shake}} test-core

# Test card-compiler
test-compiler:
    @test -f {{shake}} || just bootstrap
    @{{shake}} test-compiler

# REPL for cardpg-core
repl-core:
    @test -f {{shake}} || just bootstrap
    @{{shake}} repl-core

# REPL for cardpg-server
repl-server:
    @test -f {{shake}} || just bootstrap
    @{{shake}} repl-server

# Deploy to prod (smart rebuild)
deploy-prod:
    @test -f {{shake}} || just bootstrap
    @{{shake}} deploy-prod

# Deploy to prod (force rebuild)
deploy-rebuild:
    @test -f {{shake}} || just bootstrap
    @{{shake}} deploy-rebuild

# Format Haskell code
format:
    @test -f {{shake}} || just bootstrap
    @{{shake}} format

# Check Haskell code formatting
format-check:
    @test -f {{shake}} || just bootstrap
    @{{shake}} format-check

