# Justfile generated by shake-build
# DO NOT EDIT MANUALLY: Run 'just gen-just' to update

default: card-data

_build-shake:
    cabal build shake-build

# Compiles all card data to VTT JSON
card-data: _build-shake
    cabal run shake-build -- card-data

# Syncs card data from Google Sheets
sync: _build-shake
    cabal run shake-build -- sync

# Clean build artifacts
clean: _build-shake
    cabal run shake-build -- clean

# Regenerate the Justfile
gen-just: _build-shake
    cabal run shake-build -- gen-just

# Generate TypeScript types
gen-types: _build-shake
    cabal run shake-build -- gen-types

# Build cardpg-core
build-core: _build-shake
    cabal run shake-build -- build-core

# Build cardpg-server
build-server: _build-shake
    cabal run shake-build -- build-server

