version: "0.5"

processes:
  server:
    command: cabal run exe:cardpg-server-reflex
    is_restart: true
    shutdown:
      signal: 15
    availability:
      restart: "on_failure"
    ready_log_line: "Starting CardPG Reflex Server on port 3004"

  client:
    # We use ghcid for the client to allow fast reloads
    # Note: We need a temporary config for ghci prompt
    command: |
      GHCI_CONFIG=$(mktemp)
      echo ':set prompt "ghci> "' > "$GHCI_CONFIG"
      ghcid --command "cabal repl exe:cardpg-client-reflex --repl-options=\"-ghci-script $GHCI_CONFIG\"" --run --warnings
    depends_on:
      server:
        condition: process_log_ready
      tailwind-reflex:
        condition: process_started
    is_restart: false
    shutdown:
      signal: 15

  tailwind-reflex:
    command: ./node_modules/.bin/tailwindcss -i ./styles/input.css -o ./static/output.css --watch=always
    working_dir: cardpg-client-reflex
    is_restart: true
    shutdown:
      signal: 15

  assets-proxy:
    command: npm run proxy
    working_dir: cardpg-client-reflex
    is_restart: true
    depends_on:
      client:
        condition: process_started
    shutdown:
      signal: 15
