// Generated by cardpg-codegen. DO NOT EDIT.

export type ResourceType = "red" | "yellow" | "blue";

export type StackPower = IStackPower;

export interface IStackPower {
  source: ResourceType;
  modifier: number;
  conditional?: string;
}

export type Difficulty = IDifficulty;

export interface IDifficulty {
  attribute: ResourceType;
  value: number;
}

export type TextStyle = "bold" | "italic" | "gameKeyword";

export type Inline = ITextRun | IColorValue | IDifficultyValue | IBreak;

export interface ITextRun {
  type: "textRun";
  style?: TextStyle;
  content: string;
}

export interface IColorValue {
  type: "colorValue";
  value: StackPower;
}

export interface IDifficultyValue {
  type: "difficultyValue";
  difficulty: Difficulty;
}

export interface IBreak {
  type: "break";
}

export type RichText = IRichText;

export type IRichText = Inline[];

export type RichString = IRichString;

export type IRichString = RichText;

export type Block = IParagraph | IHeader | IRule | IBulletList;

export interface IParagraph {
  type: "paragraph";
  data: RichString;
}

export interface IHeader {
  type: "header";
  data: RichString;
}

export interface IRule {
  type: "rule";
}

export interface IBulletList {
  type: "bulletList";
  data: RichString[];
}

export type PassiveDef = IPassiveDef;

export interface IPassiveDef {
  bonus: StackPower;
  condition?: string;
}

export type AttackDef = IAttackDef;

export interface IAttackDef {
  power: StackPower;
  resistedBy: ResourceType;
  effect?: RichText;
}

export type GeneralDef = IGeneralDef;

export interface IGeneralDef {
  name: string;
  cost?: RichText;
  difficulty?: Difficulty;
  effect: RichText;
}

export type StanceDef = IStanceDef;

export interface IStanceDef {
  duration: string;
  effect: RichText;
}

export type ChannelDef = IChannelDef;

export interface IChannelDef {
  duration: string;
  effect: RichText;
}

export type PrimeDef = IPrimeDef;

export interface IPrimeDef {
  trigger: string;
  reaction: Rule;
}

export type TaskDef = ITaskDef;

export interface ITaskDef {
  name: string;
  check?: Difficulty;
  time?: RichText;
  cost?: RichText;
  effect: RichText;
}

export type TriggerDef = ITriggerDef;

export interface ITriggerDef {
  trigger: string;
  effect: RichText;
}

export type Rule = IRuleRuleAttack | IRuleRuleGeneral | IRuleRuleTask | IRuleRuleTrigger | IRuleRuleStance | IRuleRuleChannel | IRuleRulePrime | IRuleRuleNarrative | IRuleRulePassive;

export interface IRuleRuleAttack {
  type: "attack";
  data: AttackDef;
}

export interface IRuleRuleGeneral {
  type: "general";
  data: GeneralDef;
}

export interface IRuleRuleTask {
  type: "task";
  data: TaskDef;
}

export interface IRuleRuleTrigger {
  type: "trigger";
  data: TriggerDef;
}

export interface IRuleRuleStance {
  type: "stance";
  data: StanceDef;
}

export interface IRuleRuleChannel {
  type: "channel";
  data: ChannelDef;
}

export interface IRuleRulePrime {
  type: "prime";
  data: PrimeDef;
}

export interface IRuleRuleNarrative {
  type: "narrative";
  data: RichText;
}

export interface IRuleRulePassive {
  type: "passive";
  data: PassiveDef;
}

export type Stats = IStats;

export interface IStats {
  red: number;
  yellow: number;
  blue: number;
}

export type SpecialDefend = ISpecialDefend;

export interface ISpecialDefend {
  red: ResourceType;
  yellow: ResourceType;
  blue: ResourceType;
}

export type CoreCard = ICoreCard;

export interface ICoreCard {
  type: "coreCard";
  name: string;
  tags?: string[];
  stats: Stats;
  cost?: number;
  rules?: Rule[];
  flavor?: RichText;
}

export type ItemCard = IItemCard;

export interface IItemCard {
  type: "itemCard";
  name: string;
  tags?: string[];
  flavor?: RichText;
  weight?: number;
  value?: number;
  traits?: string[];
  passive?: string;
  defense?: number;
  resilience?: number;
  burden?: number;
}

export type NatureCard = INatureCard;

export interface INatureCard {
  type: "natureCard";
  name: string;
  tags?: string[];
  flavor?: RichText;
  traits?: string[];
  passive?: string;
  defense?: number;
  resilience?: number;
  specialDefend?: SpecialDefend;
}

export type TalentCard = ITalentCard;

export interface ITalentCard {
  type: "talentCard";
  name: string;
  tags?: string[];
  flavor?: RichText;
  traits?: string[];
  passive?: string;
  defense?: number;
}

export type GeneralActionDef = IGeneralActionDef;

export interface IGeneralActionDef {
  name: string;
  description: string;
  attribute: ResourceType;
  difficulty: number;
}

export type EncounterMechanics = IEncounterMechanics;

export interface IEncounterMechanics {
  combat?: string[];
  challenges?: GeneralActionDef[];
  effects?: string[];
}

export type EncounterCard = IEncounterCard;

export interface IEncounterCard {
  type: "encounterCard";
  name: string;
  tags?: string[];
  narrative: RichText;
  options?: string[];
  mechanics?: EncounterMechanics;
}

export type ConsequenceCard = IConsequenceCard;

export interface IConsequenceCard {
  type: "consequenceCard";
  name: string;
  tags?: string[];
  passive?: string;
  effects?: string[];
  severity: number;
  notes?: string;
  rules?: Rule[];
}

export type ActorDefinition = IActorDefinition;

export interface IActorDefinition {
  name: string;
  tags?: string[];
  items: ItemCard[];
  nature: NatureCard[];
  deck: CoreCard[];
}

export type ActorState = IActorState;

export interface IActorState {
  name: string;
  actorType: string;
  coreState: CoreCardState;
  tableState: TableState;
  spatial: SpatialState;
  plannedMove?: [number, number];
}

export type AssetState = IInCollection | IEquipped | IStashed | ITrait | ICondition;

export interface IInCollection {
  type: "inCollection";
}

export interface IEquipped {
  type: "equipped";
  data: EquipSlot;
}

export interface IStashed {
  type: "stashed";
}

export interface ITrait {
  type: "trait";
}

export interface ICondition {
  type: "condition";
}

export type CoreCardState = ICoreCardState;

export interface ICoreCardState {
  deck: string[];
  hand: string[];
  discard: string[];
  planned?: PlannedAction;
  defending: string[];
  inPlay: {[k in string]?: CorePlayState};
  registry: {[k in string]?: CoreCard};
  revealed?: RevealedEffect;
}

export type CorePlayState = IStance | IAttachedTo;

export interface IStance {
  type: "stance";
}

export interface IAttachedTo {
  type: "attachedTo";
  data: string;
}

export type EquipSlot = "slotMainHand" | "slotOffHand" | "slotBody" | "slotAccessory" | "slotUnspecified";

export type TableState = ITableState;

export interface ITableState {
  assets: {[k in string]?: AssetState};
  registry: {[k in string]?: TableCard};
  consequences: string[];
  consequenceRegistry: {[k in string]?: ConsequenceCard};
}

export type TableCard = ITCItem | ITCNature | ITCTalent | ITCConsequence;

export interface ITCItem {
  type: "tCItem";
  data: ItemCard;
}

export interface ITCNature {
  type: "tCNature";
  data: NatureCard;
}

export interface ITCTalent {
  type: "tCTalent";
  data: TalentCard;
}

export interface ITCConsequence {
  type: "tCConsequence";
  data: ConsequenceCard;
}

export type Token = IToken;

export interface IToken {
  id: string;
  actorId: string;
  x: number;
  y: number;
  size: number;
}

export type ActorGameEvent = IActorGameEvent;

export interface IActorGameEvent {
  actorId: string;
  event: GameEvent;
}

export type GameEvent = ICardsCreated | IDeckShuffled | ICardDrawn | ICardDefended | IMovePlanned | IActorMoved | IActionPlanned | IPlanCanceled | IActionRevealed | IDefenseEnded | IIllegalAction | IStatusAdded | IStatusRemoved | IConsequenceAdded | IConsequenceRemoved;

export interface ICardsCreated {
  type: "cardsCreated";
  data: string[];
}

export interface IDeckShuffled {
  type: "deckShuffled";
}

export interface ICardDrawn {
  type: "cardDrawn";
  data: string;
}

export interface ICardDefended {
  type: "cardDefended";
  data: string;
}

export interface IMovePlanned {
  type: "movePlanned";
  data: [number, number];
}

export interface IActorMoved {
  type: "actorMoved";
  data: [number, number];
}

export interface IActionPlanned {
  type: "actionPlanned";
  data: PlannedAction;
}

export interface IPlanCanceled {
  type: "planCanceled";
  data: PlannedAction;
}

export interface IActionRevealed {
  type: "actionRevealed";
  data: [PlannedAction, RevealedEffect];
}

export interface IDefenseEnded {
  type: "defenseEnded";
  data: string[];
}

export interface IIllegalAction {
  type: "illegalAction";
  data: [PlannedAction, string];
}

export interface IStatusAdded {
  type: "statusAdded";
  data: [string, string];
}

export interface IStatusRemoved {
  type: "statusRemoved";
  data: [string, string];
}

export interface IConsequenceAdded {
  type: "consequenceAdded";
  data: number;
}

export interface IConsequenceRemoved {
  type: "consequenceRemoved";
  data: string;
}

export type RevealedEffect = IREPass | IREAttack | IREInvalid;

export interface IREPass {
  type: "rEPass";
}

export interface IREAttack {
  type: "rEAttack";
  data: RealizedAttack;
}

export interface IREInvalid {
  type: "rEInvalid";
  data: string;
}

export type Command = IDrawIntent | IDefendIntent | IPlanMove | IPlanAction | IPlanNarrative | ICancelPlanIntent | IStartResolutionIntent | IEndDefenseIntent | IReshuffleIntent | IAddStatusIntent | IRemoveStatusIntent | IAddConsequenceIntent | IRemoveConsequenceIntent | IDiscardCardsIntent | IReturnToDeckIntent | IEndRoundIntent | IPassIntent | IChatIntent;

export interface IDrawIntent {
  type: "drawIntent";
  actorId: string;
}

export interface IDefendIntent {
  type: "defendIntent";
  actorId: string;
}

export interface IPlanMove {
  type: "planMove";
  actorId: string;
  x: number;
  y: number;
}

export interface IPlanAction {
  type: "planAction";
  actorId: string;
  actionCardId: string;
  resourceCardIds: string[];
}

export interface IPlanNarrative {
  type: "planNarrative";
  actorId: string;
  cardIds: string[];
  color: ResourceType;
}

export interface ICancelPlanIntent {
  type: "cancelPlanIntent";
  actorId: string;
}

export interface IStartResolutionIntent {
  type: "startResolutionIntent";
  actorId: string;
}

export interface IEndDefenseIntent {
  type: "endDefenseIntent";
  actorId: string;
}

export interface IReshuffleIntent {
  type: "reshuffleIntent";
  actorId: string;
}

export interface IAddStatusIntent {
  type: "addStatusIntent";
  actorId: string;
  statusType: string;
  destination: string;
}

export interface IRemoveStatusIntent {
  type: "removeStatusIntent";
  actorId: string;
  statusType: string;
  targetCardId?: string;
}

export interface IAddConsequenceIntent {
  type: "addConsequenceIntent";
  actorId: string;
  severity?: number;
}

export interface IRemoveConsequenceIntent {
  type: "removeConsequenceIntent";
  actorId: string;
  cardId: string;
}

export interface IDiscardCardsIntent {
  type: "discardCardsIntent";
  actorId: string;
  cardIds: string[];
}

export interface IReturnToDeckIntent {
  type: "returnToDeckIntent";
  actorId: string;
  cardIds: string[];
}

export interface IEndRoundIntent {
  type: "endRoundIntent";
  actorId: string;
}

export interface IPassIntent {
  type: "passIntent";
  actorId: string;
}

export interface IChatIntent {
  type: "chatIntent";
  chatSenderId?: string;
  content: string;
}

export type ClientMessage = IJoin | IGameCommand;

export interface IJoin {
  type: "join";
  name: string;
  id?: string;
}

export interface IGameCommand {
  type: "gameCommand";
  command: Command;
}

export type ServerMessage = IWelcome | IBroadcastMessage | IClientJoined | IClientLeft | IErrorMessage | IMultiMessage | IGameStateUpdate | INewLogs;

export interface IWelcome {
  type: "welcome";
  yourClientId: string;
  connectedClients: string[];
  initialActors: StateUpdate[];
  phase: Phase;
  history: LogEntry[];
}

export interface IBroadcastMessage {
  type: "broadcastMessage";
  fromClientId: string;
  payload: ActorGameEvent[];
}

export interface IClientJoined {
  type: "clientJoined";
  newClientName: string;
  newClientId: string;
}

export interface IClientLeft {
  type: "clientLeft";
  leftClientId: string;
}

export interface IErrorMessage {
  type: "errorMessage";
  error: string;
}

export interface IMultiMessage {
  type: "multiMessage";
  messages: ServerMessage[];
}

export interface IGameStateUpdate {
  type: "gameStateUpdate";
  updates: StateUpdate[];
  newPhase?: Phase;
}

export interface INewLogs {
  type: "newLogs";
  logs: LogEntry[];
}

export type StateUpdate = IStateUpdate;

export interface IStateUpdate {
  updateActorId: string;
  updateActorState: ActorState;
}

export type SpatialState = ISpatialState;

export interface ISpatialState {
  posX: number;
  posY: number;
  size: number;
  mapId?: string;
}

export type ActionStack = IActionStack;

export interface IActionStack {
  actionCard: string;
  resources: string[];
}

export type NarrativeStack = INarrativeStack;

export interface INarrativeStack {
  cards: string[];
  color: ResourceType;
}

export type PlannedAction = IPStandard | IPNarrative | IPPass;

export interface IPStandard {
  type: "pStandard";
  data: ActionStack;
}

export interface IPNarrative {
  type: "pNarrative";
  data: NarrativeStack;
}

export interface IPPass {
  type: "pPass";
}

export type RealizedAttack = IRealizedAttack;

export interface IRealizedAttack {
  attackCard: string;
  attackStrength: number;
  defenseColor: ResourceType;
}

export type Phase = "planning" | "resolution";

export type LogPayload = ILogInfo | ILogChat | ILogAttack | ILogDefense;

export interface ILogInfo {
  type: "logInfo";
  content: string;
}

export interface ILogChat {
  type: "logChat";
  content: string;
}

export interface ILogAttack {
  type: "logAttack";
  attack: RealizedAttack;
  resourceCardIds?: string[];
}

export interface ILogDefense {
  type: "logDefense";
  defenseActorId: string;
  ended: boolean;
  snapshot?: string[];
}

export type LogEntry = ILogEntry;

export interface ILogEntry {
  id: string;
  timestamp: number;
  sender: string;
  senderId?: string;
  payload: LogPayload;
}