# Weeder configuration
# https://github.com/ocharles/weeder

# Entry points for the project
roots = [
  # Main executables
  "^Main.main$",
  "server:exe:server",
  "server:exe:server-devel",
  "client-reflex:exe:client-reflex",
  "client-reflex:exe:cardpg-static",

  # Tests are entry points
  "core:test:core-test",
  "server:test:server-test",
  "client-reflex:test:client-reflex-test",
]

type-class-roots = true