cabal-version: 3.0
name:          cardpg-server
version:       0.1.0.0
license:       BSD-3-Clause
license-file:  LICENSE
author:        Antigravity
maintainer:    antigravity@example.com
build-type:    Simple

common project-config
  default-language:   GHC2021
  default-extensions:
    DerivingStrategies
    DuplicateRecordFields
    MultiWayIf
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    QuantifiedConstraints
    RecordWildCards
    TemplateHaskell

library
  import:          project-config

  -- cabal-fmt: expand src
  exposed-modules:
    CardPG.Server.ChatParser
    CardPG.Server.Config
    CardPG.Server.Connection
    CardPG.Server.DB
    CardPG.Server.Dispatch
    CardPG.Server.Engine
    CardPG.Server.Game
    CardPG.Server.Loader
    CardPG.Server.Presenter
    CardPG.Server.ReflexConnection
    CardPG.Server.Scenario
    CardPG.Server.Session
    CardPG.Server.Types

  hs-source-dirs:  src
  build-depends:
    , aeson
    , aeson-typescript
    , base               >=4.7 && <5
    , beam-automigrate
    , beam-core
    , beam-migrate
    , beam-postgres
    , cardpg-api
    , cardpg-core
    , containers
    , directory
    , filepath
    , megaparsec
    , mtl
    , optics
    , postgresql-simple
    , random
    , resource-pool
    , stm
    , text
    , time
    , uuid
    , websockets
    , yaml

executable cardpg-server
  import:         project-config
  main-is:        Main.hs
  other-modules:
  hs-source-dirs: app
  build-depends:
    , aeson
    , base               >=4.7 && <5
    , beam-core
    , beam-postgres
    , bytestring
    , cardpg-core
    , cardpg-server
    , containers
    , mtl
    , postgresql-simple
    , random
    , resource-pool
    , stm
    , text
    , time
    , uuid
    , websockets

executable cardpg-server-reflex
  import:         project-config
  main-is:        ReflexMain.hs
  hs-source-dirs: app
  build-depends:
    , aeson
    , base               >=4.7 && <5
    , cardpg-core
    , cardpg-server
    , network
    , postgresql-simple
    , resource-pool
    , text
    , websockets

test-suite cardpg-server-test
  import:         project-config
  type:           exitcode-stdio-1.0
  main-is:        Main.hs

  -- cabal-fmt: expand test -Main
  other-modules:
    GameTest
    InMemoryTest
    JsonTest
    ScenarioTest

  hs-source-dirs: test
  build-depends:
    , aeson
    , base              >=4.7 && <5
    , bytestring
    , cardpg-api
    , cardpg-core
    , cardpg-server
    , containers
    , directory
    , filepath
    , mtl
    , optics
    , random
    , tasty
    , tasty-hunit
    , tasty-quickcheck
    , text
    , yaml
