cabal-version:      3.0
name:               card-compiler
version:            0.1.0.0
synopsis:           Compiles JSON card definitions to YAML using Haskell parsers
license:            BSD-3-Clause
author:             Antigravity
maintainer:         antigravity@google.com
build-type:         Simple

common project-config
    ghc-options: -Wall
    default-language: GHC2021
    default-extensions:
        -- Project Standard
        DerivingStrategies
        DuplicateRecordFields
        NoFieldSelectors
        OverloadedLabels
        OverloadedRecordDot
        OverloadedStrings
        QuantifiedConstraints
        RecordWildCards
        TemplateHaskell

        -- Control Flow
        MultiWayIf

executable card-compiler
    import:           project-config
    main-is:          Main.hs
    other-modules:    CardCompiler.Parser
                    , CardCompiler.VttExporter
                    , CardCompiler
    -- other-extensions:
    build-depends:    base >= 4.16 && < 5
                    , aeson
                    , bytestring
                    , text
                    , yaml
                    , megaparsec
                    , optics
                    , vector
                    , cardpg-core
                    , filepath
                    , directory
                    , containers
    hs-source-dirs:   src

test-suite card-compiler-test
    import:           project-config
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    hs-source-dirs:   test, src
    other-modules:    CardCompiler.Parser
    build-depends:    base
                    , hspec
                    , QuickCheck
                    , hspec-megaparsec
                    , cardpg-core
                    , text
                    , aeson
                    , vector
                    , megaparsec
                    , containers
