// Auto-generated by code/scripts/build_vtt_data.py
import { T, I, createCardTemplate } from './cardData';

export const STATUS_CARDS = [
  createCardTemplate('Fatigue', 1, 1, 1, 
    [], 
    undefined, undefined, 'fatigue', undefined),
  createCardTemplate('Injury', 0, 0, 0, 
    [T('If this card is in your hand at the end of the Resolve Step, expend it.')], 
    undefined, undefined, 'wound', undefined),
];