module Rules.Justfile where

import Development.Shake

-- | Regenerate the Justfile based on the definitions
generateJustfile :: [(String, String, Action ())] -> Action ()
generateJustfile defs = do
  let justfileContent =
        unlines $
          [ "# Justfile generated by shake-build"
          , "# DO NOT EDIT MANUALLY: Run 'just gen-just' to update"
          , ""
          , "default: build"
          , ""
          , "# Define output binary path"
          , "shake := '_build/shake-build'"
          , ""
          , "# Helper to ensure shake binary exists"
          , "bootstrap:"
          , "    cabal install shake-build --installdir=_build --install-method=copy --overwrite-policy=always"
          , ""
          ]
            ++ concatMap
              ( \(name, desc, _) ->
                  if name == "gen-just"
                    then
                      -- gen-just always uses cabal run to ensure it runs with latest source code changes
                      [ "# " ++ desc
                      , name ++ ":"
                      , "    cabal run shake-build -- " ++ name
                      , ""
                      ]
                    else
                      -- Other targets use the bootstrapped binary
                      [ "# " ++ desc
                      , name ++ ":"
                      , "    @test -f {{shake}} || just bootstrap"
                      , "    @{{shake}} " ++ name
                      , ""
                      ]
              )
              defs
  writeFileChanged "Justfile" justfileContent
