cabal-version:      3.0
name:                cardpg-codegen
version:             0.1.0.0
build-type:          Simple


common project-config
    default-language: GHC2021
    default-extensions:
        DerivingStrategies
        DuplicateRecordFields
        NoFieldSelectors
        OverloadedLabels
        OverloadedRecordDot
        OverloadedStrings
        QuantifiedConstraints
        RecordWildCards
        TemplateHaskell
        MultiWayIf

executable codegen
  import: project-config
  main-is:             Main.hs
  other-modules:       DeriveSpecialized, TypeScriptInstances
  build-depends:       base >= 4.7 && < 5
                     , aeson-typescript
                     , cardpg-core
                     , cardpg-server
                     , text
                     , template-haskell
                     , containers
