{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell #-}

module Main where

import Data.Aeson.TypeScript.TH
import Data.Proxy
import System.IO (writeFile)

import CardPG.Core.Types (ResourceType, StackPower)
import CardPG.Core.NonEmptyText (NonEmptyText)
import CardPG.Core.RichText (TextStyle, Inline, RichString, Block)
import CardPG.Core.RuleDefs (PassiveDef, AttackDef, DefendDef, GeneralDef, StanceDef, ChannelDef, PrimeDef, Rule)
import CardPG.Core.Card (Stats, CoreCard, ItemCard, NatureCard, TalentCard, GeneralActionDef, EncounterMechanics, EncounterCard, ConsequenceCard, Actor)
import CardPG.Server.Types (ClientMessage, ServerMessage)

import Data.List (intercalate)
import Data.Text (pack, unpack, replace)
import System.Environment (getArgs)

main :: IO ()
main = do
  args <- getArgs
  let outputFile = case args of
        (x:_) -> x
        []    -> "types.ts"
  
  let declarations = formatTSDeclarations (
        (getTypeScriptDeclarations (Proxy :: Proxy ResourceType)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy StackPower)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy NonEmptyText)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy TextStyle)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy Inline)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy RichString)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy Block)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy PassiveDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy AttackDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy DefendDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy GeneralDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy StanceDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy ChannelDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy PrimeDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy Rule)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy Stats)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy CoreCard)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy ItemCard)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy NatureCard)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy TalentCard)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy GeneralActionDef)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy EncounterMechanics)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy EncounterCard)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy ConsequenceCard)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy Actor)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy ClientMessage)) <>
        (getTypeScriptDeclarations (Proxy :: Proxy ServerMessage))
        )

  let exportedDeclarations = unpack $ replace "interface " "export interface " $ replace "type " "export type " $ pack declarations

  writeFile outputFile $
    "// Generated by cardpg-codegen. DO NOT EDIT.\n\n" ++ exportedDeclarations
