{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Main where

import Data.Aeson.TypeScript.TH
import Data.List (intercalate)
import Data.Proxy
import Data.Set (Set)
import Data.Set qualified as Set
import Data.Text (pack, replace, unpack)
import Data.Typeable (TypeRep, typeRep)
import System.Environment (getArgs)
import System.IO (writeFile)
import TypeScriptInstances
  ( ActorDefinition
  , AttackDef
  , ConsequenceCard
  , CoreCard
  , EncounterCard
  , GeneralDef
  , ItemCard
  , NatureCard
  , OngoingDef
  , Rule
  , TalentCard
  , TaskDef
  , TriggerDef
  )

import CardPG.Core.Card (EncounterMechanics, GeneralActionDef, SpecialDefend, Stats)
import CardPG.Core.NonEmptyText (NonEmptyText)
import CardPG.Core.Primitives
  ( ActorId
  , CardLocation
  , Difficulty
  , EquipSlot
  , ResourceType
  , StackPower
  )
import CardPG.Core.RichText (Block, Inline, RichString, RichText, TextStyle)
import CardPG.Core.RuleDefs (PassiveDef)
import CardPG.Core.State
  ( ActionStack
  , AssetState
  , CoreCardState
  , CorePlayState
  , GameEvent
  , NarrativeStack
  , PlannedAction
  , RealizedAttack
  , RevealedEffect
  , SpatialState
  , TableCard
  , TableState
  )
import CardPG.Server.Types
  ( ActorGameEvent
  , AdminCommand
  , ClientMessage
  , Command
  , LogEntry
  , LogPayload
  , Phase
  , ServerMessage
  , StateUpdate
  , Token
  )
import CardPG.Server.Types.Wire qualified as Wire

collectDeclarations :: [TSType] -> [TSDeclaration]
collectDeclarations roots =
  let (decls, _) = visit roots Set.empty
   in decls

visit :: [TSType] -> Set TypeRep -> ([TSDeclaration], Set TypeRep)
visit [] visited = ([], visited)
visit ((TSType p) : xs) visited =
  let rep = typeRep p
   in if Set.member rep visited
        then visit xs visited
        else
          let decls = getTypeScriptDeclarations p
              parents = getParentTypes p
              visited' = Set.insert rep visited
              (restDecls, finalVisited) = visit (parents ++ xs) visited'
           in (decls ++ restDecls, finalVisited)

main :: IO ()
main = do
  args <- getArgs
  let outputFile = case args of
        (x : _) -> x
        [] -> "types.ts"

  let declarations =
        formatTSDeclarations $
          collectDeclarations
            [ TSType (Proxy :: Proxy AdminCommand)
            , TSType (Proxy :: Proxy ClientMessage)
            , TSType (Proxy :: Proxy ServerMessage)
            , TSType (Proxy :: Proxy ActorDefinition)
            , TSType (Proxy :: Proxy EncounterCard)
            ]

  let exportedDeclarations =
        unpack $
          replace "interface " "export interface " $
            replace "type " "export type " $
              pack declarations

  writeFile outputFile $
    "// Generated by cardpg-codegen. DO NOT EDIT.\n\n" ++ exportedDeclarations
