// Generated by cardpg-codegen. DO NOT EDIT.

export type ResourceType = "red" | "yellow" | "blue";

export type StackPower = IStackPower;

export interface IStackPower {
  source: ResourceType;
  modifier: number;
  conditional?: string;
}

export type NonEmptyText = INonEmptyText;

export type INonEmptyText = string;

export type TextStyle = "bold" | "italic" | "gameKeyword";

export type Inline = ITextRun | IColorValue | IDifficultyValue | IBreak;

export interface ITextRun {
  type: "textRun";
  style?: TextStyle;
  content: NonEmptyText;
}

export interface IColorValue {
  type: "colorValue";
  value: StackPower;
}

export interface IDifficultyValue {
  type: "difficultyValue";
  difficulty: Difficulty;
}

export interface IBreak {
  type: "break";
}

export type RichString = IRichString;

export type IRichString = Inline[];

export type Block = IParagraph | IHeader | IRule | IBulletList;

export interface IParagraph {
  type: "paragraph";
  data: RichString;
}

export interface IHeader {
  type: "header";
  data: RichString;
}

export interface IRule {
  type: "rule";
}

export interface IBulletList {
  type: "bulletList";
  data: RichString[];
}

export type PassiveDef = IPassiveDef;

export interface IPassiveDef {
  bonus: StackPower;
  condition?: NonEmptyText;
}

export type AttackDef = IAttackDef;

export interface IAttackDef {
  power: StackPower;
  resistedBy: ResourceType;
  effect?: RichString;
}

export type GeneralDef = IGeneralDef;

export interface IGeneralDef {
  name: NonEmptyText;
  cost?: RichString;
  difficulty?: Difficulty;
  effect: RichString;
}

export type StanceDef = IStanceDef;

export interface IStanceDef {
  duration: NonEmptyText;
  effect: RichString;
}

export type ChannelDef = IChannelDef;

export interface IChannelDef {
  duration: NonEmptyText;
  effect: RichString;
}

export type PrimeDef = IPrimeDef;

export interface IPrimeDef {
  trigger: NonEmptyText;
  reaction: Rule;
}

export type TaskDef = ITaskDef;

export interface ITaskDef {
  name: NonEmptyText;
  check?: Difficulty;
  time?: RichString;
  cost?: RichString;
  effect: RichString;
}

export type TriggerDef = ITriggerDef;

export interface ITriggerDef {
  trigger: NonEmptyText;
  effect: RichString;
}

export type Rule = IRuleAttack | IRuleGeneral | IRuleTask | IRuleTrigger | IRuleStance | IRuleChannel | IRulePrime | IRuleNarrative | IRulePassive;

export interface IRuleAttack {
  type: "attack";
  data: AttackDef;
}

export interface IRuleGeneral {
  type: "general";
  data: GeneralDef;
}

export interface IRuleTask {
  type: "task";
  data: TaskDef;
}

export interface IRuleTrigger {
  type: "trigger";
  data: TriggerDef;
}

export interface IRuleStance {
  type: "stance";
  data: StanceDef;
}

export interface IRuleChannel {
  type: "channel";
  data: ChannelDef;
}

export interface IRulePrime {
  type: "prime";
  data: PrimeDef;
}

export interface IRuleNarrative {
  type: "narrative";
  data: RichString;
}

export interface IRulePassive {
  type: "passive";
  data: PassiveDef;
}

export type Stats = IStats;

export interface IStats {
  red: number;
  yellow: number;
  blue: number;
}

export type CoreCard = ICoreCard;

export interface ICoreCard {
  type: "coreCard";
  id?: string;
  name: NonEmptyText;
  tags?: string[];
  stats: Stats;
  cost?: number;
  rules?: Rule[];
  flavor?: RichString;
}

export type ItemCard = IItemCard;

export interface IItemCard {
  type: "itemCard";
  id?: string;
  name: NonEmptyText;
  tags?: string[];
  flavor?: RichString;
  weight?: number;
  value?: number;
  traits?: string[];
  passive?: string;
  defense?: number;
  resilience?: number;
}

export type NatureCard = INatureCard;

export interface INatureCard {
  id?: string;
  name: NonEmptyText;
  tags?: string[];
  flavor?: RichString;
  traits?: string[];
  passive?: string;
  defense?: number;
  resilience?: number;
}

export type TalentCard = ITalentCard;

export interface ITalentCard {
  id?: string;
  name: NonEmptyText;
  tags?: string[];
  flavor?: RichString;
  traits?: string[];
  passive?: string;
  defense?: number;
}

export type GeneralActionDef = IGeneralActionDef;

export interface IGeneralActionDef {
  name: string;
  description: string;
  attribute: ResourceType;
  difficulty: number;
}

export type EncounterMechanics = IEncounterMechanics;

export interface IEncounterMechanics {
  combat?: string[];
  challenges?: GeneralActionDef[];
  effects?: string[];
}

export type EncounterCard = IEncounterCard;

export interface IEncounterCard {
  id?: string;
  name: NonEmptyText;
  tags?: string[];
  narrative: RichString;
  options?: string[];
  mechanics?: EncounterMechanics;
}

export type ConsequenceCard = IConsequenceCard;

export interface IConsequenceCard {
  type: "consequenceCard";
  id?: string;
  name: NonEmptyText;
  tags?: string[];
  passive?: string;
  effects?: string[];
  notes?: string;
  rules?: Rule[];
}

export type Actor = IActor;

export interface IActor {
  name: string;
  tags?: string[];
  items: ItemCard[];
  deck: CoreCard[];
}

export type ClientMessage = IJoin | IBroadcast;

export interface IJoin {
  tag: "Join";
  name: string;
}

export interface IBroadcast {
  tag: "Broadcast";
  payload: any;
}

export type ServerMessage = IWelcome | IBroadcastMessage | IClientJoined | IClientLeft | IErrorMessage;

export interface IWelcome {
  tag: "Welcome";
  yourClientId: string;
  connectedClients: string[];
  history: any[];
}

export interface IBroadcastMessage {
  tag: "BroadcastMessage";
  fromClientId: string;
  payload: any;
}

export interface IClientJoined {
  tag: "ClientJoined";
  newClientName: string;
  newClientId: string;
}

export interface IClientLeft {
  tag: "ClientLeft";
  leftClientId: string;
}

export interface IErrorMessage {
  tag: "ErrorMessage";
  error: string;
}