cabal-version: 3.4
name:          client-reflex
version:       0.1.0.0
synopsis:      Reflex-DOM frontend for CardPG
license:       MIT
author:        Antigravity
maintainer:    antigravity@example.com
build-type:    Simple

common warnings
  ghc-options: -Wall

common project-config
  default-language:   GHC2021
  default-extensions:
    DefaultSignatures
    DerivingStrategies
    DuplicateRecordFields
    LambdaCase
    MultiWayIf
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    QuantifiedConstraints
    RecordWildCards
    RecursiveDo
    TemplateHaskell
    TypeFamilies

library
  import:          warnings
  import:          project-config
  build-depends:
    , aeson
    , api
    , base
    , bytestring
    , containers
    , core
    , data-default
    , optics-core
    , random
    , reflex-dom
    , reflex-dom-core
    , text
    , uuid
    , vector
    , yaml

  exposed-modules:
    Frontend.App
    Frontend.Card
    Frontend.Catalog
    Frontend.Game.Hand
    Frontend.Game.PlannedAction
    Frontend.Game.Sidebar
    Frontend.Html
    Frontend.Style
    Frontend.Svg
    Frontend.UI.Scaler

  hs-source-dirs:  src

executable client-reflex
  import:         warnings
  import:         project-config
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N
  main-is:        Main.hs
  build-depends:
    , api
    , base
    , client-reflex
    , http-types
    , jsaddle-warp
    , reflex-dom-core
    , text
    , uuid
    , wai
    , wai-app-static
    , warp
    , websockets

  hs-source-dirs: app

executable cardpg-static
  import:         warnings
  import:         project-config
  main-is:        StaticMain.hs
  build-depends:
    , api
    , base
    , bytestring
    , client-reflex
    , core
    , filepath
    , reflex-dom-core
    , text
    , yaml

  hs-source-dirs: app
