cabal-version: 3.4
name:          cardpg-client-reflex
version:       0.1.0.0
synopsis:      Reflex-DOM frontend for CardPG
license:       MIT
author:        Antigravity
maintainer:    antigravity@example.com
build-type:    Simple

common warnings
  ghc-options: -Wall

common project-config
  default-language:   GHC2021
  default-extensions:
    DerivingStrategies
    DuplicateRecordFields
    MultiWayIf
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    QuantifiedConstraints
    RecordWildCards
    RecursiveDo
    TemplateHaskell

executable cardpg-client-reflex
  import:         warnings
  import:         project-config
  main-is:        Main.hs
  build-depends:
    , base
    , cardpg-core
    , containers
    , jsaddle-warp
    , optics-core
    , reflex-dom
    , text
    , vector

  other-modules:
    Frontend.Card
    Frontend.Card.Common
    Frontend.Html
    Frontend.Style

  hs-source-dirs: src
