{-# LANGUAGE OverloadedStrings #-}
{- FOURMOLU_DISABLE -}

-- |
-- Module: Core.Glossary.Generated
-- Description: Machine-generated keyword glossary data from design/rules/keyword-glossary.md.
--
-- DO NOT EDIT THIS FILE DIRECTLY.
-- To update, edit design/rules/keyword-glossary.md and run:
--   cabal run tools-hs:exe:audit-index -- --fix
-- or:
--   cabal run tools-hs:exe:keyword-mod -- codegen
module Core.Glossary.Generated
  ( glossary
  , glossaryEntries
  ) where

import Core.Glossary.Types (Glossary, GlossaryEntry (..), fromList)
import Core.Language (TextStyle (..))
import Core.NonEmptyText (unsafeNonEmptyText)
import Core.RichText (Inline (..), RichText (..))
import Data.List.NonEmpty qualified as NE

-- | Canonical keyword glossary constructed at compile time.
glossary :: Glossary
glossary = fromList glossaryEntries

-- | All canonical glossary entries in the order defined in the markdown.
glossaryEntries :: [GlossaryEntry]
glossaryEntries =
  [   GlossaryEntry
    { canonical = "Color"
    , aliases = ["Colors"]
    , slug = "color"
    , category = "The Three Colors"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "How approaches and abilities are classified and actions are adjudicated. Values are ")
          NE.:|
            [ TextRun (Just GameKeyword) (unsafeNonEmptyText "Red")
            , TextRun Nothing (unsafeNonEmptyText ", ")
            , TextRun (Just GameKeyword) (unsafeNonEmptyText "Yellow")
            , TextRun Nothing (unsafeNonEmptyText ", and ")
            , TextRun (Just GameKeyword) (unsafeNonEmptyText "Blue")
            , TextRun Nothing (unsafeNonEmptyText ". See ")
            , MarkdownLink (unsafeNonEmptyText "colors-of-action.md") (unsafeNonEmptyText "Colors of Action")
            , TextRun Nothing (unsafeNonEmptyText " for detailed classifications.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Red"
    , aliases = []
    , slug = "red"
    , category = "The Three Colors"
    , theme = Just "red"
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "One of the game's ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Colors") Nothing
            , TextRun Nothing (unsafeNonEmptyText ". The color of Force, Endurance, Presence, Passion, Dominion.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Yellow"
    , aliases = []
    , slug = "yellow"
    , category = "The Three Colors"
    , theme = Just "yellow"
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "One of the game's ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Colors") Nothing
            , TextRun Nothing (unsafeNonEmptyText ". The color of Speed, Precision, Perception, Cunning, Finesse.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Blue"
    , aliases = []
    , slug = "blue"
    , category = "The Three Colors"
    , theme = Just "blue"
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "One of the game's ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Colors") Nothing
            , TextRun Nothing (unsafeNonEmptyText ". The color of Intellect, Planning, Discipline, Lore, Intrigue.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Strength"
    , aliases = []
    , slug = "strength"
    , category = "Action Resolution"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "How strong or powerful an action or hazard is. Set by a character's action card, a challenge card, or GM adjudication. The character carrying out a general action or defending against an attack must meet the strength of the challenge in their action resolution.") NE.:| [])
    }
  ,   GlossaryEntry
    { canonical = "Impact"
    , aliases = []
    , slug = "impact"
    , category = "Action Resolution"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "The total number of cards flipped from the deck during a defense or general action. ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Impact") Nothing
            , TextRun Nothing (unsafeNonEmptyText " is divided by ")
            , Wikilink (unsafeNonEmptyText "Defense") Nothing
            , TextRun Nothing (unsafeNonEmptyText " to determine the number of consequences suffered.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Defense"
    , aliases = []
    , slug = "defense"
    , category = "Action Resolution"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "One of the key stats for resolving actions. ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Defense") Nothing
            , TextRun Nothing (unsafeNonEmptyText " tells you how many cards of ")
            , Wikilink (unsafeNonEmptyText "Impact") Nothing
            , TextRun Nothing (unsafeNonEmptyText " translate into taking one ")
            , Wikilink (unsafeNonEmptyText "Consequence") Nothing
            , TextRun Nothing (unsafeNonEmptyText ". Unarmored characters default to ")
            , Wikilink (unsafeNonEmptyText "Defense") Nothing
            , TextRun Nothing (unsafeNonEmptyText " 1.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Resilience"
    , aliases = []
    , slug = "resilience"
    , category = "Action Resolution"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "The number of ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Consequences") Nothing
            , TextRun Nothing (unsafeNonEmptyText " a character can suffer at a given ")
            , Wikilink (unsafeNonEmptyText "Severity") Nothing
            , TextRun Nothing (unsafeNonEmptyText " level before new consequences escalate to the next severity tier. Defaults to 1 if unarmored.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Consequence"
    , aliases = ["Consequences"]
    , slug = "consequence"
    , category = "Action Resolution"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "Cards suffered from physical trauma, strain, or environmental friction when ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Impact") Nothing
            , TextRun Nothing (unsafeNonEmptyText " meets or exceeds ")
            , Wikilink (unsafeNonEmptyText "Defense") Nothing
            , TextRun Nothing (unsafeNonEmptyText ". Suffix/plural uses ")
            , Wikilink (unsafeNonEmptyText "Consequences") Nothing
            , TextRun Nothing (unsafeNonEmptyText ".")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Severity"
    , aliases = ["Severity 1", "Severity 2", "Severity 3"]
    , slug = "severity"
    , category = "Action Resolution"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "The escalation tier of suffered ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Consequences") Nothing
            , TextRun Nothing (unsafeNonEmptyText ". Severity 1 represents minor friction/wear")
            , Break
            , TextRun Nothing (unsafeNonEmptyText " Severity 2 represents serious injury/vulnerability")
            , Break
            , TextRun Nothing (unsafeNonEmptyText " Severity 3 indicates incapacitation.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Burden"
    , aliases = []
    , slug = "burden"
    , category = "Equipment & Fatigue"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "The metabolic cost of armor and heavy equipment. When you perform a ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Fatigue Cycle") Nothing
            , TextRun Nothing (unsafeNonEmptyText ", you must add extra ")
            , Wikilink (unsafeNonEmptyText "Fatigue") Nothing
            , TextRun Nothing (unsafeNonEmptyText " cards to your deck equal to your total ")
            , Wikilink (unsafeNonEmptyText "Burden") Nothing
            , TextRun Nothing (unsafeNonEmptyText ".")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Fatigue"
    , aliases = ["Fatigue Cycle", "Fatigue Cards"]
    , slug = "fatigue"
    , category = "Equipment & Fatigue"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "Systemic physical exhaustion. When your deck is exhausted, a ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Fatigue Cycle") Nothing
            , TextRun Nothing (unsafeNonEmptyText " adds ")
            , Wikilink (unsafeNonEmptyText "Fatigue") Nothing
            , TextRun Nothing (unsafeNonEmptyText " cards (plus active ")
            , Wikilink (unsafeNonEmptyText "Burden") Nothing
            , TextRun Nothing (unsafeNonEmptyText ") to your expended pile before reshuffling.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Crisis Time"
    , aliases = []
    , slug = "crisis-time"
    , category = "Pacing & Play Modes"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "Turn-based, round-by-round mode for resolving combat, chases, and tense second-by-second struggles.") NE.:| [])
    }
  ,   GlossaryEntry
    { canonical = "Adventuring Time"
    , aliases = []
    , slug = "adventuring-time"
    , category = "Pacing & Play Modes"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "Fluid exploration mode used for travel, dungeon navigation, investigation, and downtime.") NE.:| [])
    }
  ,   GlossaryEntry
    { canonical = "Downtime"
    , aliases = []
    , slug = "downtime"
    , category = "Pacing & Play Modes"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "Extended periods of rest, crafting, project advancement, and long-term recovery between active adventures.") NE.:| [])
    }
  ,   GlossaryEntry
    { canonical = "Ready Hand"
    , aliases = []
    , slug = "ready-hand"
    , category = "Pacing & Play Modes"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "A pool of 0 to 4 cards maintained on the table during ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Adventuring Time") Nothing
            , TextRun Nothing (unsafeNonEmptyText " representing immediate vigilance and readiness.")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Action Stack"
    , aliases = ["Action Stacks"]
    , slug = "action-stack"
    , category = "Pacing & Play Modes"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "An Action card played from hand combined with additional cards committed to pay its resource cost.") NE.:| [])
    }
  ,   GlossaryEntry
    { canonical = "General Action"
    , aliases = ["General Actions"]
    , slug = "general-action"
    , category = "Pacing & Play Modes"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "Non-combat challenges with meaningful stakes outside combat, resolved defender-centric with success as default.") NE.:| [])
    }
  ,   GlossaryEntry
    { canonical = "Attack"
    , aliases = ["Attacks"]
    , slug = "attack"
    , category = "Action Types & Card Keywords"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "An offensive action declared in ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Crisis Time") Nothing
            , TextRun Nothing (unsafeNonEmptyText " targeting another character, setting a ")
            , Wikilink (unsafeNonEmptyText "Strength") Nothing
            , TextRun Nothing (unsafeNonEmptyText " in a chosen ")
            , Wikilink (unsafeNonEmptyText "Color") Nothing
            , TextRun Nothing (unsafeNonEmptyText ".")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Defend"
    , aliases = ["Defends"]
    , slug = "defend"
    , category = "Action Types & Card Keywords"
    , theme = Nothing
    , summary =
        RichText
          ( TextRun Nothing (unsafeNonEmptyText "A defensive reaction played or resolved to absorb incoming ")
          NE.:|
            [ Wikilink (unsafeNonEmptyText "Strength") Nothing
            , TextRun Nothing (unsafeNonEmptyText ".")
            ]
          )
    }
  ,   GlossaryEntry
    { canonical = "Stance"
    , aliases = ["Stances"]
    , slug = "stance"
    , category = "Action Types & Card Keywords"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "A persistent tactical posture remaining active across rounds until discarded or replaced.") NE.:| [])
    }
  ,   GlossaryEntry
    { canonical = "Passive"
    , aliases = []
    , slug = "passive"
    , category = "Action Types & Card Keywords"
    , theme = Nothing
    , summary =
        RichText (TextRun Nothing (unsafeNonEmptyText "A card property that is continuously active while the card is in play or held in hand.") NE.:| [])
    }
  ]
