{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE ScopedTypeVariables #-}

module Main where

import Data.Aeson.TypeScript.TH
import Data.Proxy
import Data.Set (Set)
import Data.Set qualified as Set
import Data.Text (pack, replace, unpack)
import Data.Typeable (TypeRep, typeRep)
import System.Environment (getArgs)
import System.IO (writeFile)

-- Import the TypeScriptInstances module to bring all instances into scope.
-- The instances are discovered transitively from the root types below.
import TypeScriptInstances ()

import Api.Types (AdminCommand, ClientMessage, ServerMessage)

collectDeclarations :: [TSType] -> [TSDeclaration]
collectDeclarations roots =
  let (decls, _) = visit roots Set.empty
   in decls

visit :: [TSType] -> Set TypeRep -> ([TSDeclaration], Set TypeRep)
visit [] visited = ([], visited)
visit ((TSType p) : xs) visited =
  let rep = typeRep p
   in if Set.member rep visited
        then visit xs visited
        else
          let decls = getTypeScriptDeclarations p
              parents = getParentTypes p
              visited' = Set.insert rep visited
              (restDecls, finalVisited) = visit (parents ++ xs) visited'
           in (decls ++ restDecls, finalVisited)

main :: IO ()
main = do
  args <- getArgs
  let outputFile = case args of
        (x : _) -> x
        [] -> "types.ts"

  let declarations =
        formatTSDeclarations $
          collectDeclarations
            [ TSType (Proxy :: Proxy AdminCommand)
            , TSType (Proxy :: Proxy ClientMessage)
            , TSType (Proxy :: Proxy ServerMessage)
            ]

  let exportedDeclarations =
        unpack $
          replace "interface " "export interface " $
            replace "type " "export type " $
              pack declarations

  writeFile outputFile $
    "// Generated by cardpg-codegen. DO NOT EDIT.\n\n" ++ exportedDeclarations
