{-# LANGUAGE OverloadedStrings #-}

module Main where

import Control.Monad (forM)
import Data.Function (on)
import Data.List qualified as List
import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.IO qualified as T
import Options.Applicative qualified as OA
import System.Directory (doesDirectoryExist, listDirectory)
import System.FilePath (takeExtension, (</>))
import System.IO (IOMode (ReadMode), hSetEncoding, utf8, withFile)

import Reflex.AtomicCss.Core (Prop (..), renderAll)
import Reflex.AtomicCss.DSL qualified as S
import Reflex.AtomicCss.Parser (scanContent, staticStyles)

-- | CLI Options
data Options = Options
  { scanDirs :: [FilePath]
  , outCss :: FilePath
  }

optionsParser :: OA.Parser Options
optionsParser =
  Options
    <$> OA.many
      ( OA.strOption
          ( OA.long "scan-dir"
              <> OA.metavar "DIR"
              <> OA.help "Directory to scan for Haskell source files containing styles"
          )
      )
    <*> OA.strOption
      ( OA.long "out"
          <> OA.metavar "FILE"
          <> OA.help "Output CSS file path"
          <> OA.value "client/static/atomic.css"
          <> OA.showDefault
      )

header :: Text
header =
  "/* This file is auto-generated by reflex-atomic-css gen-css */\n"

readUtf8File :: FilePath -> IO Text
readUtf8File path = withFile path ReadMode $ \h -> do
  hSetEncoding h utf8
  T.hGetContents h

main :: IO ()
main = do
  opts <- OA.execParser optsInfo
  let dirs =
        if null opts.scanDirs
          then ["client/src", "src", "client/app", "app"]
          else opts.scanDirs
  putStrLn $ "Scanning directories: " ++ show dirs

  files <- concat <$> mapM findHaskellFiles dirs
  putStrLn $ "Scanning " <> show (length files) <> " Haskell files..."

  allContents <- forM files readUtf8File
  let scanned = concatMap scanContent allContents

  let allContentsText = T.concat allContents
      usedIn name variant =
        (variant <> " " <> name) `T.isInfixOf` allContentsText
          || (variant <> " S." <> name) `T.isInfixOf` allContentsText
          || ("S." <> variant <> " " <> name) `T.isInfixOf` allContentsText
          || ("S." <> variant <> " S." <> name) `T.isInfixOf` allContentsText

  let baseStaticProps = concatMap snd staticStyles
      allProps = baseStaticProps ++ scanned
      uniqueBase = List.nubBy ((==) `on` (.propClassName)) allProps

      staticHoverProps = concat [[S.hoverProp p] | (name, props) <- staticStyles, usedIn name "hover", p <- props]
      staticActiveProps = concat [[S.activeProp p] | (name, props) <- staticStyles, usedIn name "active", p <- props]
      staticLastProps = concat [[S.lastChildProp p] | (name, props) <- staticStyles, usedIn name "lastChild", p <- props]

      scannedHoverProps = map S.hoverProp scanned
      scannedActiveProps = map S.activeProp scanned
      scannedLastProps = map S.lastChildProp scanned

      withVariants =
        uniqueBase
          ++ staticHoverProps
          ++ staticActiveProps
          ++ staticLastProps
          ++ scannedHoverProps
          ++ scannedActiveProps
          ++ scannedLastProps
      unique = List.nubBy ((==) `on` (.propClassName)) withVariants

  T.writeFile opts.outCss (header <> renderAll unique)
  putStrLn $ "Done. Wrote " <> opts.outCss <> " with " <> show (length unique) <> " rules."
  where
    optsInfo =
      OA.info
        (optionsParser OA.<**> OA.helper)
        ( OA.fullDesc
            <> OA.progDesc "Generate utility CSS stylesheet from Reflex Style DSL usages"
            <> OA.header "gen-css - Atomic CSS generator"
        )

-- | Recursive file finder
findHaskellFiles :: FilePath -> IO [FilePath]
findHaskellFiles top = do
  isDir <- doesDirectoryExist top
  if isDir
    then do
      entries <- listDirectory top
      paths <- forM entries $ \e -> findHaskellFiles (top </> e)
      return $ concat paths
    else
      return [top | takeExtension top == ".hs"]
