{-# LANGUAGE OverloadedStrings #-}

module Main where

import Control.Monad (forM)
import Data.Function (on)
import Data.List qualified as List
import Data.Text (Text)
import Data.Text.IO qualified as T
import Options.Applicative qualified as OA
import System.Directory (doesDirectoryExist, listDirectory)
import System.FilePath (takeExtension, (</>))
import System.IO (IOMode (ReadMode), hSetEncoding, utf8, withFile)

import Reflex.AtomicCss.Core (Prop (..), renderAll)
import Reflex.AtomicCss.Parser (scanContent, staticStyles)

-- | CLI Options
data Options = Options
  { scanDirs :: [FilePath]
  , outCss :: FilePath
  }

optionsParser :: OA.Parser Options
optionsParser =
  Options
    <$> OA.many
      ( OA.strOption
          ( OA.long "scan-dir"
              <> OA.metavar "DIR"
              <> OA.help "Directory to scan for Haskell source files containing styles"
          )
      )
    <*> OA.strOption
      ( OA.long "out"
          <> OA.metavar "FILE"
          <> OA.help "Output CSS file path"
          <> OA.value "client/static/atomic.css"
          <> OA.showDefault
      )

header :: Text
header =
  "/* This file is auto-generated by reflex-atomic-css gen-css */\n"

readUtf8File :: FilePath -> IO Text
readUtf8File path = withFile path ReadMode $ \h -> do
  hSetEncoding h utf8
  T.hGetContents h

main :: IO ()
main = do
  opts <- OA.execParser optsInfo
  let dirs =
        if null opts.scanDirs
          then ["client/src", "src", "client/app", "app"]
          else opts.scanDirs
  putStrLn $ "Scanning directories: " ++ show dirs

  files <- concat <$> mapM findHaskellFiles dirs
  putStrLn $ "Scanning " <> show (length files) <> " Haskell files..."

  allContents <- forM files readUtf8File
  let scanned = concatMap scanContent allContents

  let baseStaticProps = concatMap snd staticStyles
      allProps = scanned ++ baseStaticProps
      unique = List.nubBy ((==) `on` (.propClassName)) allProps

  T.writeFile opts.outCss (header <> renderAll unique)
  putStrLn $ "Done. Wrote " <> opts.outCss <> " with " <> show (length unique) <> " rules."
  where
    optsInfo =
      OA.info
        (optionsParser OA.<**> OA.helper)
        ( OA.fullDesc
            <> OA.progDesc "Generate utility CSS stylesheet from Reflex Style DSL usages"
            <> OA.header "gen-css - Atomic CSS generator"
        )

-- | Recursive file finder
findHaskellFiles :: FilePath -> IO [FilePath]
findHaskellFiles top = do
  isDir <- doesDirectoryExist top
  if isDir
    then do
      entries <- listDirectory top
      paths <- forM entries $ \e -> findHaskellFiles (top </> e)
      return $ concat paths
    else
      return [top | takeExtension top == ".hs"]
