[project]
name = "cardpg-scripting"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
  "clifun",
  "PyYAML",
  "types-PyYAML",
  "gspread",
  "websockets>=15.0.1",
]

[tool.uv.sources]
clifun = { path = "../../../dev/clifun", editable = true }

[tool.pyright]
venvPath = "."
venv = ".venv"

