cabal-version: 3.0
name:          api
version:       0.1.0.0
license:       BSD-3-Clause
license-file:  LICENSE
author:        Antigravity
maintainer:    antigravity@example.com
build-type:    Simple

common project-config
  default-language:   GHC2021
  default-extensions:
    DefaultSignatures
    DerivingStrategies
    DuplicateRecordFields
    MultiWayIf
    NoFieldSelectors
    OverloadedLabels
    OverloadedRecordDot
    OverloadedStrings
    QuantifiedConstraints
    RecordWildCards
    TemplateHaskell
    TypeFamilies

  ghc-options:        -Wall

library
  import:          project-config
  hs-source-dirs:  src

  -- cabal-fmt: expand src
  exposed-modules:
    Api.Reflex
    Api.Request
    Api.Types

  build-depends:
    , aeson
    , aeson-gadt-th
    , base                    >=4.7 && <5
    , constraints-extras
    , containers
    , core
    , dependent-sum
    , dependent-sum-template
    , random
    , reflex-gadt-api
    , some
    , text
    , time
    , uuid-types
